### ISSUE TITLE
"TypeError: explode() expects parameter 2 to be string, null given"

### ISSUE THREAD

**Issue by espeespe** [enanobots/m2-attribute-pagination#1]
TypeError: explode() expects parameter 2 to be string, null given in /var/www/vendor/enanobots/m2-attribute-pagination/src/module-attribute-pagination/Block/Adminhtml/Attribute/Edit/Options/Options.php:70

with visualSwatch configuration like this:

![image](https://user-images.githubusercontent.com/91457457/134866625-d5dbe31f-fa56-46a0-898e-9fc1a43f8e30.png)

![image](https://user-images.githubusercontent.com/91457457/134867034-bdfff3a4-40ff-43d8-8a22-78b978c8b8d6.png)

**Comment by jakwinkler** [comment]
@espeespe Thank you for reporting the issue. 
I haven't checked on VisualSwatches yet, might require few changes in the code for this to work. 
I'm swamped with work by the end of the week + there will be a small update for options sort order.
However, if you can create a PR for visualSwatches, I will process it probably on the same day.

**Comment by jakwinkler** [comment]
@espeespe can you describe the way it can be replicated?
I can't experience the issue on 2.4.2 / 2.3.6
![image](https://user-images.githubusercontent.com/4256191/134880715-de824e6f-0927-460c-b4bc-d22b611f5c06.png)
visualSwatch is handled by different `class` / `block`

**Comment by espeespe** [comment]
I can see only one difference:
![image](https://user-images.githubusercontent.com/91457457/134936430-3d9d090e-9b47-4877-ae57-77a1c7075b2c.png)

Swatch color is not selected on my store. It;s empty. Mayby because of that. Or mayby because my products are imported from csv and there are some data gaps. I will check on clear luma.

**Comment by espeespe** [comment]
Strange, on clear luma, magento 2.4.2 pagination appears for one second, and disappear. But without error about null value 
<img width="1759" alt="image" src="https://user-images.githubusercontent.com/91457457/134940098-5b80bb8d-c09b-4829-9278-958cff6a032c.png">

**Comment by jakwinkler** [comment]
@espeespe it should not be visible at all for swatches, it might show/disappear if you change the attribute type.

**Comment by espeespe** [comment]
So with text swatch it works fine. great work!

**Comment by jakwinkler** [comment]
@espeespe are you still able to reproduce the error?

**Comment by jakwinkler** [comment]
I was not able to replicate this issue. Closing.
If the issue keeps repeating, please provide detailed feedback.

**Comment by axelosd** [comment]
Same error at 2.4.3-p1

> TypeError: explode() expects parameter 2 to be string, null given in Nanobots/AttributeOptionPager/Block/Adminhtml/Attribute/Edit/Options/Options.php:73

I was able to bypass the error by changing

```
if ($type === 'select' || $type === 'multiselect') {
    $defaultValues = explode(',', $attribute->getDefaultValue());
    $inputType = $type === 'select' ? 'radio' : 'checkbox';
} else {
    $defaultValues = [];
    $inputType = '';
}
```

with

```
if ($type === 'select' || $type === 'multiselect') {
    if($attribute->getDefaultValue() != null){
        $defaultValues = explode(',', $attribute->getDefaultValue());                
    }else{
        $defaultValues = [];
    }    
    $inputType = $type === 'select' ? 'radio' : 'checkbox';        
} else {
     $defaultValues = [];
     $inputType = '';
}
```

to check if getDefaultValue() is null
