### ISSUE TITLE
Sort options across pages

### ISSUE THREAD

**Issue by Morgy93** [enanobots/m2-attribute-pagination#2]
Hello,

I don't see an option to sort the options across pages.

You can sort the options within one page:

![image](https://user-images.githubusercontent.com/7961978/142444968-268d0f78-bc0a-4393-be94-8603ffd4fc63.png)

But if you want to drag an option from page 2 to page 1 then I don't see a possibility.

**Comment by enanobots** [comment]
We are currently swamped with our projects, feel free to create a pull request once you add this. 
All that is required here is to change `hidden input type` into `input text` 
Drag and drop should be fully disabled in this case.

**Comment by enanobots** [comment]
Version 1.0.2 removes drag & drop and adds a new `Sort Order` field. 
@Morgy93 hope this helps :-)

**Comment by Morgy93** [comment]
@enanobots Great, thanks!

But how about having both? 😁 
Sort input field if you need/want to do it manually/across pages.
Drag and drop if you want to sort within one page. (Like Magento 2 default)

For me this sounds like the perfect solution. 😊

**Comment by enanobots** [comment]
We will leave it like that for a while.
If you want to combine both features, feel free to provide a pull request. 
However we are working on other modules now :-) 
This issue will remain closed.
