### ISSUE TITLE
Magento 2.4.5 - Does this work with Magento Spectrum Admin theme?

### ISSUE THREAD

**Issue by parkktech** [enanobots/m2-attribute-pagination#4]
I have installed this to 2.4.5 and I cannot get it to work. Im not sure if it's because the new site has a new admin theme "Magento Spectrum" or if something else is conflicting with it.

**Comment by enanobots** [comment]
@strattas does it work if you disable all the theme backend modules?

**Comment by parkktech** [comment]
@enanobots Sorry I didn't respond after posting this. We had something extending the same file already.  So I got it working. 
However we have over 50k values in our attribute and this still trying to load the whole array when editing the Attribute.  A nice improvment would be to improve the query to not to load the 50k values in the memory before trying to paginate.

**Comment by enanobots** [comment]
I'm closing this as it is custom theme related.

**Comment by enanobots** [comment]
@strattas  please check the PR that was merged, maybe it was related to the requireJS
https://github.com/enanobots/m2-attribute-pagination/pull/6
