### ISSUE TITLE
Sample text attribute values are 100 thousand. The page is slow or does not open. How to increase loading speed?

### ISSUE THREAD

**Issue by jtscorpjaxon** [enanobots/m2-attribute-pagination#7]
Thank you, you did a great job. Well done boys. I extended to the Text swatch.
![image](https://github.com/enanobots/m2-attribute-pagination/assets/25705183/6926d9e5-b920-4412-b02f-e9d30bf3f363)

`namespace Jtscorp\FasterAttribute\Block\Adminhtml\Attribute\Edit\Options;

/**
 * Block Class for Text Swatch
 *
 * @api
 * @since 100.0.2
 */
class Text extends \Jtscorp\FasterAttribute\Block\Adminhtml\Attribute\Edit\Options\AbstractSwatch
{
    /**
     * @var string
     */
    protected $_template = 'Jtscorp_FasterAttribute::catalog/product/attribute/text.phtml';

    /**
     * Return json config for text option JS initialization
     *
     * @return array
     * @since 100.1.0
     */
    public function getJsonConfig()
    {
        $values = [];
        foreach ($this->getOptionValues() as $value) {
            $values[] = $value->getData();
        }

        $data = [
            'attributesData' => $values,
            'isSortable' => (int)(!$this->getReadOnly() && !$this->canManageOptionDefaultOnly()),
            'isReadOnly' => (int)$this->getReadOnly()
        ];

        return json_encode($data);
    }
}
`

**Comment by jakwinkler** [comment]
Not sure what needs to be done here, will you create a PR ?

**Comment by jakwinkler** [comment]
This was solved in this PR:
https://github.com/enanobots/m2-attribute-pagination/pull/8 

version 1.0.5 has these changes.
